baseURL = "https://brucewayne98.github.io"
languageCode = "en-us"
title = "Bharath Kumar"
theme = "hugo-noir"

# Enable multilingual support
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[params]
  name = "Bharath Kumar"
  location = "Bengaluru"
  description = "A passionate developer and blogger sharing insights on technology, coding, and life."
  profile_image = "/images/profile.jpg"
  
  # Social links
  github = "https://github.com/BruceWayne98"
  linkedin = "https://www.linkedin.com/in/bharath-kumar-r98"
  email = "maxmod98@gmail.com"

[languages]
  [languages.en]
    languageName = "English"
    title = "Bharath Kumar"
    weight = 1
    contentDir = "content/en"
    
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        pageRef = "/"
        weight = 1
      
      [[languages.en.menu.main]]
        name = "About"
        pageRef = "/about"
        weight = 2
      
      [[languages.en.menu.main]]
        name = "Blog"
        pageRef = "/blogs"
        weight = 3
      
      [[languages.en.menu.main]]
        name = "Projects"
        pageRef = "/projects"
        weight = 4
      
      [[languages.en.menu.main]]
        name = "Experience"
        pageRef = "/experience"
        weight = 5
      
      [[languages.en.menu.main]]
        name = "Papers"
        pageRef = "/papers"
        weight = 6
      
      [[languages.en.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = true

[outputs]
  home = ["HTML", "RSS"]
